services:
  web:
    build: .
    command: sh -c "echo 'Waiting for DB...' && \
                 echo 'DB is ready!' && \
                 python manage.py migrate && \
                 python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

# environment:
#   - LANG=C.UTF-8